# Uncomment the next line to define a global platform for your project
use_frameworks!

platform :ios, '11.0'

workspace 'EaseIMKit.xcworkspace'


target 'EaseIMKitDemo' do
  platform :ios, '11.0'
  project '../EaseIMKitDemo/EaseIMKitDemo.xcodeproj'
  #pod 'Masonry'
  #pod 'Hyphenate'
  #pod 'EaseIMKit', :path => './'
end

target 'EaseIMKit' do
  project './EaseIMKit.xcodeproj'
  pod 'Hyphenate'
  pod 'EMVoiceConvert', '~> 0.1.0'
end


