# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace 'EaseIMKitDemo.xcworkspace'

target 'EaseIMKitDemo' do
  pod 'HyphenateChat'
  pod 'Masonry'
  pod 'EaseIMKit',  :path => "../"
end


