#!/bin/bash

# SETTING
# location of XCODE docset
ROOT_DIR=.
EXPORT_ROOT=${ROOT_DIR}/export

# docset env
DOCSET_ROOT=${EXPORT_ROOT}/docset
DOCSET_NAME=com.easemob.documentation.sdk.docset
DOCSET_DIR=${DOCSET_ROOT}/${DOCSET_NAME}

# raw doc dir
#RAW_DOC_DIR=${EXPORT_ROOT}/SDKHelper

# include env
INCLUDE_DIR=${EXPORT_ROOT}/include

# location of html code document, generated by headerdoc2html
DOCUMENT_DIR=$DOCSET_DIR/Contents/Resources/Documents

# location of hautelook templates, Info.plist Nodes.xml
DOCSET_TEMPLATE_DIR=./templates

# location of our source code, where headerdoc2html will spider through
SOURCE_DIR=${INCLUDE_DIR}

# clear screen
clear

# delete old docset and start from fresh, this will kill XCODE if its running.  good for development only, comment out for production.
rm -rf $DOCSET_DIR

# create document directory
mkdir -p $DOCUMENT_DIR

# copy doc to DOCUMENT_DIR
#cp -r ${RAW_DOC_DIR}/* ${DOCUMENT_DIR}

# generate html code document for source code.  -j will recognize java comment tag ex. /** */
# https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/HeaderDoc/usage/usage.html#//apple_ref/doc/uid/TP40001215-CH337-SW2
#headerdoc2html -j -o $DOCUMENT_DIR $SOURCE_DIR
headerdoc2html -o $DOCUMENT_DIR $SOURCE_DIR

# generate main index file. -d will generate Tokens.xml for us.
#
# http://opensource.apple.com/source/headerdoc/
# https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/HeaderDoc/usage/usage.html#//apple_ref/doc/uid/TP40001215-CH337-SW1
#
gatherheaderdoc -d $DOCUMENT_DIR

echo "DOCSET_DIR: " $DOCSET_DIR
echo "DOCUMENT_DIR: " $DOCUMENT_DIR
echo "SOURCE_DIR: " $SOURCE_DIR
echo "DOCSET_TEMPLATE_DIR: " $DOCSET_TEMPLATE_DIR

# copy required template files for apple docset
cp $DOCSET_TEMPLATE_DIR/Info.plist $DOCSET_DIR/Contents/
cp $DOCSET_TEMPLATE_DIR/Nodes.xml   $DOCSET_DIR/Contents/Resources/
cp $DOCUMENT_DIR/Tokens.xml         $DOCSET_DIR/Contents/Resources/

# create and validate apple docset indexes
/Applications/Xcode.app/Contents/Developer/usr/bin/docsetutil index -verbose -debug $DOCSET_DIR
/Applications/Xcode.app/Contents/Developer/usr/bin/docsetutil validate -verbose -debug $DOCSET_DIR
