platform :ios, '7.0'

# Import CocoaPods sources
source 'https://github.com/CocoaPods/Specs.git'

target 'EaseUI' do
#pod 'MWPhotoBrowser', '~> 2.1.1'
#pod 'MJRefresh','~> 3.0.6'
#pod 'EaseMobSDKFull', :git => 'https://github.com/easemob/sdk-ios-cocoapods-integration.git'
end

#target 'ChatDemo-UI3.0’ do
#pod 'EaseMobSDK', :git => 'https://github.com/easemob/sdk-ios-cocoapods.git'
#end
